name: notary
on:
  workflow_dispatch:
    inputs:
      buildId:
        description: Build ID
        required: true
        type: string
      bashbrewArch:
        description: Bashbrew Architecture
        required: true
        type: choice
        options:
          - amd64
          - i386
          - windows-amd64
      firstTag: # informational only, because "run-name" can't be set to a useful value otherwise
        description: First Tag (informational only)
        type: string
      windowsVersion:
        description: Windows Version
        type: choice
        options:
          - '' # without this, it's technically "required" 🙃
          - '2022'
          - '2019'
run-name: '${{ inputs.bashbrewArch }}: ${{ inputs.firstTag }} (${{ inputs.buildId }})'

concurrency:
  group: ${{ github.event.inputs.buildId }}
  cancel-in-progress: false
defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'
env:
  BUILD_ID: ${{ inputs.buildId }}
  BASHBREW_ARCH: ${{ inputs.bashbrewArch }}
jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/shared.yml
    with:
      buildId: ${{ inputs.buildId }}
      bashbrewArch: ${{ inputs.bashbrewArch }}
      firstTag: ${{ inputs.firstTag }}
      windowsVersion: ${{ inputs.windowsVersion }}
    secrets: inherit
